// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#include "../ui.h"

void ui_FwUpdate_screen_init(void)
{
ui_FwUpdate = lv_obj_create(NULL);
lv_obj_clear_flag( ui_FwUpdate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Title3 = lv_label_create(ui_FwUpdate);
lv_obj_set_width( ui_Title3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Title3, 0 );
lv_obj_set_y( ui_Title3, -220 );
lv_obj_set_align( ui_Title3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title3,"Firmware Update");

ui_Panel_Content3 = lv_obj_create(ui_FwUpdate);
lv_obj_set_width( ui_Panel_Content3, 320);
lv_obj_set_height( ui_Panel_Content3, 440);
lv_obj_set_x( ui_Panel_Content3, 0 );
lv_obj_set_y( ui_Panel_Content3, 20 );
lv_obj_set_align( ui_Panel_Content3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_Content3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_Content3, lv_color_hex(0xF8F8F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Content3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel_Content3, lv_color_hex(0xDCE5ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Panel_Content3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel_Content3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel_Content3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Content3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel_Content3);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -23 );
lv_obj_set_y( ui_Label1, 25 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Firmware Update is loading...");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x4B4A4A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Panel_Content3);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 111 );
lv_obj_set_y( ui_Label2, 48 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"15%");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x343333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_Panel_Content3);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 216);
lv_obj_set_height( ui_Bar2, 15);
lv_obj_set_x( ui_Bar2, -21 );
lv_obj_set_y( ui_Bar2, 48 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );

ui_Image1 = lv_img_create(ui_FwUpdate);
lv_img_set_src(ui_Image1, &ui_img_download_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 129
lv_obj_set_x( ui_Image1, -1 );
lv_obj_set_y( ui_Image1, -80 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelButton3 = lv_obj_create(ui_FwUpdate);
lv_obj_set_width( ui_PanelButton3, 300);
lv_obj_set_height( ui_PanelButton3, 70);
lv_obj_set_x( ui_PanelButton3, 10 );
lv_obj_set_y( ui_PanelButton3, -10 );
lv_obj_set_align( ui_PanelButton3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_PanelButton3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnBack2 = lv_btn_create(ui_PanelButton3);
lv_obj_set_width( ui_BtnBack2, 270);
lv_obj_set_height( ui_BtnBack2, 40);
lv_obj_set_align( ui_BtnBack2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnBack2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LbBtnCancel = lv_label_create(ui_PanelButton3);
lv_obj_set_width( ui_LbBtnCancel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbBtnCancel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LbBtnCancel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LbBtnCancel,"Cancel");

lv_obj_add_event_cb(ui_BtnBack2, ui_event_BtnBack2, LV_EVENT_ALL, NULL);

}
