// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Time = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Time, -140 );
lv_obj_set_y( ui_Time, -230 );
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Time,"10:15");

ui_AMPM = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_AMPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AMPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AMPM, -110 );
lv_obj_set_y( ui_AMPM, -230 );
lv_obj_set_align( ui_AMPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_AMPM,"AM");

ui_Date = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_Date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Date, -130 );
lv_obj_set_y( ui_Date, -210 );
lv_obj_set_align( ui_Date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Date,"07/10/23");

ui_Panel_Content = lv_obj_create(ui_HomeScreen);
lv_obj_set_width( ui_Panel_Content, 320);
lv_obj_set_height( ui_Panel_Content, 440);
lv_obj_set_x( ui_Panel_Content, 0 );
lv_obj_set_y( ui_Panel_Content, 20 );
lv_obj_set_align( ui_Panel_Content, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_Content, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_Content, lv_color_hex(0xF8F8F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Content, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel_Content, lv_color_hex(0xDCE5ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Panel_Content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel_Content, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel_Content, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Number_Humi_1 = lv_label_create(ui_Panel_Content);
lv_obj_set_width( ui_Number_Humi_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Number_Humi_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Number_Humi_1, 0 );
lv_obj_set_y( ui_Number_Humi_1, 40 );
lv_obj_set_align( ui_Number_Humi_1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Number_Humi_1,"35.00");
lv_obj_set_style_text_color(ui_Number_Humi_1, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Number_Humi_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Number_Humi_1, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Number_Temp_1 = lv_label_create(ui_Panel_Content);
lv_obj_set_width( ui_Number_Temp_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Number_Temp_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Number_Temp_1, 0 );
lv_obj_set_y( ui_Number_Temp_1, 80 );
lv_obj_set_align( ui_Number_Temp_1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Number_Temp_1,"25.00");
lv_obj_set_style_text_color(ui_Number_Temp_1, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Number_Temp_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Number_Temp_1, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Number_Calc_1 = lv_label_create(ui_Panel_Content);
lv_obj_set_width( ui_Number_Calc_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Number_Calc_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Number_Calc_1, -25 );
lv_obj_set_y( ui_Number_Calc_1, 130 );
lv_obj_set_align( ui_Number_Calc_1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Number_Calc_1,"8.750");
lv_obj_set_style_text_color(ui_Number_Calc_1, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Number_Calc_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Number_Calc_1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Number_Humi_2 = lv_label_create(ui_Panel_Content);
lv_obj_set_width( ui_Number_Humi_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Number_Humi_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Number_Humi_2, 0 );
lv_obj_set_y( ui_Number_Humi_2, 180 );
lv_obj_set_align( ui_Number_Humi_2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Number_Humi_2,"35.00");
lv_obj_set_style_text_color(ui_Number_Humi_2, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Number_Humi_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Number_Humi_2, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Number_Temp_2 = lv_label_create(ui_Panel_Content);
lv_obj_set_width( ui_Number_Temp_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Number_Temp_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Number_Temp_2, -1 );
lv_obj_set_y( ui_Number_Temp_2, 220 );
lv_obj_set_align( ui_Number_Temp_2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Number_Temp_2,"25.00");
lv_obj_set_style_text_color(ui_Number_Temp_2, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Number_Temp_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Number_Temp_2, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Number_Calc_2 = lv_label_create(ui_Panel_Content);
lv_obj_set_width( ui_Number_Calc_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Number_Calc_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Number_Calc_2, -25 );
lv_obj_set_y( ui_Number_Calc_2, 270 );
lv_obj_set_align( ui_Number_Calc_2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Number_Calc_2,"3.750");
lv_obj_set_style_text_color(ui_Number_Calc_2, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Number_Calc_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Number_Calc_2, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LogBTN = lv_btn_create(ui_HomeScreen);
lv_obj_set_width( ui_LogBTN, 100);
lv_obj_set_height( ui_LogBTN, 50);
lv_obj_set_x( ui_LogBTN, -105 );
lv_obj_set_y( ui_LogBTN, 210 );
lv_obj_set_align( ui_LogBTN, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LogBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LogBTN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -110 );
lv_obj_set_y( ui_Label6, 210 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Log");

ui_Menu = lv_dropdown_create(ui_HomeScreen);
lv_dropdown_set_options( ui_Menu, "Settings\nAdjust\nCalibration\nClean Memory" );
lv_dropdown_set_text( ui_Menu, "Menu");
lv_obj_set_width( ui_Menu, 100);
lv_obj_set_height( ui_Menu, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_Menu, 0 );
lv_obj_set_y( ui_Menu, -10 );
lv_obj_set_align( ui_Menu, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_PwBTN = lv_btn_create(ui_HomeScreen);
lv_obj_set_width( ui_PwBTN, 100);
lv_obj_set_height( ui_PwBTN, 50);
lv_obj_set_x( ui_PwBTN, 105 );
lv_obj_set_y( ui_PwBTN, 210 );
lv_obj_set_align( ui_PwBTN, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PwBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PwBTN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PWR = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_PWR, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PWR, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PWR, 105 );
lv_obj_set_y( ui_PWR, 211 );
lv_obj_set_align( ui_PWR, LV_ALIGN_CENTER );
lv_label_set_text(ui_PWR,"PWR");

ui_Bar1 = lv_bar_create(ui_HomeScreen);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 35);
lv_obj_set_height( ui_Bar1, 18);
lv_obj_set_x( ui_Bar1, 131 );
lv_obj_set_y( ui_Bar1, -221 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x595959), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bar1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_BatteryState = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_BatteryState, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryState, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryState, 94 );
lv_obj_set_y( ui_BatteryState, -221 );
lv_obj_set_align( ui_BatteryState, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryState,"20%");

lv_obj_add_event_cb(ui_LogBTN, ui_event_LogBTN, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PWR, ui_event_PWR, LV_EVENT_ALL, NULL);

}
