// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t *ui_HomeScreen;
lv_obj_t *ui_Time;
lv_obj_t *ui_AMPM;
lv_obj_t *ui_Date;
lv_obj_t *ui_Panel_Content;
lv_obj_t *ui_Number_Humi_1;
lv_obj_t *ui_Number_Temp_1;
lv_obj_t *ui_Number_Calc_1;
lv_obj_t *ui_Number_Humi_2;
lv_obj_t *ui_Number_Temp_2;
lv_obj_t *ui_Number_Calc_2;
void ui_event_LogBTN( lv_event_t * e);
lv_obj_t *ui_LogBTN;
lv_obj_t *ui_Label6;
void ui_event_Menu( lv_event_t * e);
lv_obj_t *ui_Menu;
lv_obj_t *ui_PwBTN;
void ui_event_PWR( lv_event_t * e);
lv_obj_t *ui_PWR;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_BatteryState;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t *ui_SettingsScreen;
lv_obj_t *ui_Title1;
lv_obj_t *ui_Panel_Content1;


// SCREEN: ui_LogScreen
void ui_LogScreen_screen_init(void);
lv_obj_t *ui_LogScreen;
lv_obj_t *ui_Title2;
lv_obj_t *ui_Panel_Content2;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1385206223[1] = {&ui_img_1992300975};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_LogBTN( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_LogScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LogScreen_screen_init);
}
}
void ui_event_Menu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_screen_change( &ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_SettingsScreen_screen_init);
}
}
void ui_event_PWR( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      PwrDisable( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_HomeScreen_screen_init();
ui_SettingsScreen_screen_init();
ui_LogScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_HomeScreen);
}
