// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#ifndef _HL_2P_UI_H
#define _HL_2P_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_AMPM;
extern lv_obj_t *ui_Date;
extern lv_obj_t *ui_Panel_Content;
extern lv_obj_t *ui_Number_Humi_1;
extern lv_obj_t *ui_Number_Temp_1;
extern lv_obj_t *ui_Number_Calc_1;
extern lv_obj_t *ui_Number_Humi_2;
extern lv_obj_t *ui_Number_Temp_2;
extern lv_obj_t *ui_Number_Calc_2;
void ui_event_LogBTN( lv_event_t * e);
extern lv_obj_t *ui_LogBTN;
extern lv_obj_t *ui_Label6;
void ui_event_Menu( lv_event_t * e);
extern lv_obj_t *ui_Menu;
extern lv_obj_t *ui_PwBTN;
void ui_event_PWR( lv_event_t * e);
extern lv_obj_t *ui_PWR;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_BatteryState;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_Title1;
extern lv_obj_t *ui_Panel_Content1;
// SCREEN: ui_LogScreen
void ui_LogScreen_screen_init(void);
extern lv_obj_t *ui_LogScreen;
extern lv_obj_t *ui_Title2;
extern lv_obj_t *ui_Panel_Content2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1992300975);   // assets\44bee2f5-0a94-412c-86c2-14bb057a1ce8.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
