// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#ifndef _HL_2P_UI_H
#define _HL_2P_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t *ui_HomeScreen;
void ui_event_PanelValues( lv_event_t * e);
extern lv_obj_t *ui_PanelValues;
extern lv_obj_t *ui_LbValue1;
extern lv_obj_t *ui_LbValue2;
extern lv_obj_t *ui_LbValue3;
extern lv_obj_t *ui_LbUnitValue1;
extern lv_obj_t *ui_LbUnitValue2;
extern lv_obj_t *ui_LbUnitValue3;
extern lv_obj_t *ui_LbTrendValue1;
extern lv_obj_t *ui_LbTrendValue2;
extern lv_obj_t *ui_LbTrendValue3;
extern lv_obj_t *ui_LbInfoText;
extern lv_obj_t *ui_LbProbeName;
extern lv_obj_t *ui_PanelTopHeader;
extern lv_obj_t *ui_LbTitleHome;
extern lv_obj_t *ui_LbTime;
extern lv_obj_t *ui_LbAmPm;
extern lv_obj_t *ui_LbDate;
extern lv_obj_t *ui_LbBatLevel;
extern lv_obj_t *ui_LbBleLogo;
extern lv_obj_t *ui_PanelButton;
void ui_event_BtnLog( lv_event_t * e);
extern lv_obj_t *ui_BtnLog;
void ui_event_BtnLog1( lv_event_t * e);
extern lv_obj_t *ui_BtnLog1;
void ui_event_BtnLog2( lv_event_t * e);
extern lv_obj_t *ui_BtnLog2;
extern lv_obj_t *ui_LbLog;
extern lv_obj_t *ui_LbSettings;
extern lv_obj_t *ui_LbPwr;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_Title1;
extern lv_obj_t *ui_PanelTopHeader1;
extern lv_obj_t *ui_LbTitleHome1;
extern lv_obj_t *ui_LbTime1;
extern lv_obj_t *ui_LbAmPm1;
extern lv_obj_t *ui_LbDate1;
extern lv_obj_t *ui_LbBatLevel1;
extern lv_obj_t *ui_LbBleLogo1;
extern lv_obj_t *ui_Panel_Content1;
extern lv_obj_t *ui_PanelSettings;
extern lv_obj_t *ui_PanelDeviceInformation;
extern lv_obj_t *ui_LbMenuDevInf;
extern lv_obj_t *ui_PanelDeviceSettings;
extern lv_obj_t *ui_LbMenuDevInf1;
void ui_event_PanelFwUpdate( lv_event_t * e);
extern lv_obj_t *ui_PanelFwUpdate;
void ui_event_LbMenuUpdate( lv_event_t * e);
extern lv_obj_t *ui_LbMenuUpdate;
void ui_event_PanelCleanMemory( lv_event_t * e);
extern lv_obj_t *ui_PanelCleanMemory;
extern lv_obj_t *ui_LbMenuClean;
extern lv_obj_t *ui_PanelButton1;
void ui_event_BtnBack( lv_event_t * e);
extern lv_obj_t *ui_BtnBack;
extern lv_obj_t *ui_LbBtnBack;
// SCREEN: ui_LogScreen
void ui_LogScreen_screen_init(void);
extern lv_obj_t *ui_LogScreen;
extern lv_obj_t *ui_Panel_Content2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_PanelButton2;
void ui_event_BtnBack1( lv_event_t * e);
extern lv_obj_t *ui_BtnBack1;
extern lv_obj_t *ui_LbBtnBack1;
extern lv_obj_t *ui_PanelTopHeader2;
extern lv_obj_t *ui_LbTitleHome2;
extern lv_obj_t *ui_LbTime2;
extern lv_obj_t *ui_LbAmPm2;
extern lv_obj_t *ui_LbDate2;
extern lv_obj_t *ui_LbBatLevel2;
extern lv_obj_t *ui_LbBleLogo2;
extern lv_obj_t *ui_BtnGraph;
void ui_event_LbBtnGraph( lv_event_t * e);
extern lv_obj_t *ui_LbBtnGraph;
void ui_event_BtnStart( lv_event_t * e);
extern lv_obj_t *ui_BtnStart;
extern lv_obj_t *ui_LbBtnPlay;
void ui_event_BtnStop( lv_event_t * e);
extern lv_obj_t *ui_BtnStop;
extern lv_obj_t *ui_LbBtnPlay1;
// SCREEN: ui_FwUpdate
void ui_FwUpdate_screen_init(void);
extern lv_obj_t *ui_FwUpdate;
extern lv_obj_t *ui_Title3;
extern lv_obj_t *ui_Panel_Content3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_PanelButton3;
void ui_event_BtnBack2( lv_event_t * e);
extern lv_obj_t *ui_BtnBack2;
extern lv_obj_t *ui_LbBtnCancel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_download_png);   // assets\download.png
LV_IMG_DECLARE( ui_img_1992300975);   // assets\44bee2f5-0a94-412c-86c2-14bb057a1ce8.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
