// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#include "ui.h"

void change_value_probe(lv_event_t * e)
{
	// Your code here
}

void lv_btn_pwr(lv_event_t * e)
{
	// Your code here
}

void clear_memory(lv_event_t * e)
{
	// Your code here
}

void showGraph(lv_event_t * e)
{
	// Your code here
}

void start_log(lv_event_t * e)
{
	// Your code here
}

void stop_Log(lv_event_t * e)
{
	// Your code here
}
