// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void change_value_probe(lv_event_t * e);
void lv_btn_pwr(lv_event_t * e);
void clear_memory(lv_event_t * e);
void showGraph(lv_event_t * e);
void start_log(lv_event_t * e);
void stop_Log(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
