// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#include "../ui.h"


// COMPONENT Number Temp

lv_obj_t *ui_Number_Temp_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Number_Temp;
cui_Number_Temp = lv_label_create(comp_parent);
lv_obj_set_width( cui_Number_Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Number_Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Number_Temp, 0 );
lv_obj_set_y( cui_Number_Temp, 40 );
lv_obj_set_align( cui_Number_Temp, LV_ALIGN_TOP_MID );
lv_label_set_text(cui_Number_Temp,"35.00");
lv_obj_set_style_text_color(cui_Number_Temp, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Number_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Number_Temp, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NUMBER_TEMP_NUM);
children[UI_COMP_NUMBER_TEMP_NUMBER_TEMP] = cui_Number_Temp;
lv_obj_add_event_cb(cui_Number_Temp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Number_Temp, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Number_Temp_create_hook(cui_Number_Temp);
return cui_Number_Temp; 
}

