// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HL_2P

#ifndef _UI_COMP_NUMBER_TEMP_H
#define _UI_COMP_NUMBER_TEMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Number Temp
#define UI_COMP_NUMBER_TEMP_NUMBER_TEMP 0
#define _UI_COMP_NUMBER_TEMP_NUM 1
lv_obj_t *ui_Number_Temp_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
